FROM node:20.10.0-alpine3.18
RUN apk update && apk add curl
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.50.0
ADD --chown=nobody:nogroup --chmod=444 https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-linux-x86_64 /usr/local/bin/hadolint
USER node
WORKDIR /app
EXPOSE 8080
CMD ["tail", "-f", "/dev/null"]
